version: "3"
services:
  php:
    user: ${UID}:${UID}
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        TIMEZONE: ${TIMEZONE}
    env_file: .env
    container_name: ${APP_NAME}_php
    volumes:
      - ../..:/var/www
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    env_file: .env
    container_name: ${APP_NAME}_nginx
    ports:
      - "${APP_PORT_HOST}:${APP_PORT}"
    volumes:
      - ../..:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        TIMEZONE: ${TIMEZONE}
    env_file: .env
    container_name: ${APP_NAME}_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT_HOST}:${MYSQL_PORT}
    volumes:
      - db_data:/var/lib/mysql
  adminer:
    image: adminer
    env_file: .env
    container_name: ${APP_NAME}_adminer
    restart: always
    ports:
      - ${ADMINER_PORT_HOST}:${ADMINER_PORT}

volumes:
  db_data: {}